# This file explicitly configures Codemagic CI/CD for React Native (not Flutter)
project_type: react_native

workflows:
  react-native-workflow:  # New workflow name
    name: React Native Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups: []  # No groups initially to keep it simple
      node: 18.15.0
      npm: 9.5.0
      java: 11
      flutter: none  # Explicitly not Flutter
      vars:
        PROJECT_TYPE: "react_native"  # Additional clarification
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Set project type
        script: |
          echo "This is a React Native project, not Flutter"
          
      - name: Install dependencies
        script: |
          npm install
          
      - name: Make gradlew executable
        script: |
          if [ -f "$CM_BUILD_DIR/android/gradlew" ]; then
            chmod +x $CM_BUILD_DIR/android/gradlew
          fi
          
      - name: Build Android Debug
        script: |
          if [ -d "$CM_BUILD_DIR/android" ]; then
            cd android
            ./gradlew assembleDebug
          else
            echo "Android directory not found"
            exit 1
          fi
    artifacts:
      - android/app/build/outputs/**/*.apk
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - user@example.com

  # Simple fallback workflow if main one fails
  simple-build:
    name: Simple Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.15.0
      flutter: none
    scripts:
      - name: Print environment
        script: |
          echo "React Native Build"
          node --version
          npm --version
      - name: Install
        script: npm install
